name: Terraform CI

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master

      # -----------------------------
      # OPA (POLÍTICAS)
      # -----------------------------
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA Policies
        run: |
          opa eval -d policies "data.terraform.security"

      # -----------------------------
      # TERRAFORM VALIDATION
      # -----------------------------
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
